package co.edu.univalle.models;

public enum FilterType {
    //QUITAR ESTRATO
    //NO ALLOWED
    UNSIGNED,
    //PERIODO
    PERIODO,
    PERIODO_UBICACION,
    PERIODO_BILINGUE,
    PERIODO_CARACTER,
    PERIODO_JORNADA,
    PERIODO_GENERO,
    PERIODO_MUNICIPIO,
    PERIODO_INTERNET,
    PERIODO_UBICACION_BILINGUE,
    PERIODO_UBICACION_BILINGUE_CARACTER,
    PERIODO_UBICACION_BILINGUE_CARACTER_JORNADA,
    PERIODO_UBICACION_BILINGUE_CARACTER_JORNADA_GENERO,
    PERIODO_UBICACION_BILINGUE_CARACTER_JORNADA_GENERO_MUNICIPIO,
    PERIODO_UBICACION_BILINGUE_CARACTER_JORNADA_GENERO_MUNICIPIO_INTERNET
}
