#mongo config
spring:
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      port: 27017
      database: icfes_valle
      authentication-database: admin
      #uri: mongodb://localhost:27017/icfes_valle?authSource=admin&user=root?password=root
  main:
    allow-bean-definition-overriding: true