version: '3.8'

services:
  mongodb:
    build: .
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: icfes_valle
    ports:
      - '27017:27017'